"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.index import send_file
from insta485.views.index import show_post
from insta485.views.index import show_explore
from insta485.views.index import update_likes
from insta485.views.index import update_comments
from insta485.views.index import update_posts
from insta485.views.index import show_users
from insta485.views.index import show_following
from insta485.views.index import show_follower
from insta485.views.index import update_following
from insta485.views.accounts import show_account_login
from insta485.views.accounts import show_account_logout
from insta485.views.accounts import show_account_create
from insta485.views.accounts import show_account_delete
from insta485.views.accounts import show_account_edit
from insta485.views.accounts import show_account_password
from insta485.views.accounts import login_helper
from insta485.views.accounts import create_helper
from insta485.views.accounts import edit_account_helper
from insta485.views.accounts import hash_helper
from insta485.views.accounts import update_password_helper
from insta485.views.accounts import show_account
